# Dockerfile
FROM mysql:8.0

# Variables d'entorn 
ENV MYSQL_DATABASE=biblilioteca \
    MYSQL_USER=joel \
    MYSQL_PASSWORD=1234 \
    MYSQL_ROOT_PASSWORD=1234

#Permetre la exposició de dades amb el port 3306
EXPOSE 3306